#!/usr/bin/env bash

if [[ "$1" == *"help"* ]]; then
    echo "Specify a filename or it will use the directory name"
    exit
elif [ "$1" == "" ]; then
    fn=$(basename $(pwd))
else
    fn=$1
fi
echo "Creating ${fn}.tar.bz"
tar -cvf ${fn}.tar * >> /dev/null
bzip2 ${fn}.tar
